### ISSUE TITLE
Including an "En Dash" in an axis title results in a 500 error on retrieving via getImage

### ISSUE THREAD

**Issue by SpencerKaiser** [plotly/plotly-nodejs#56]
### Bug Description
Adding the [En Dash](http://www.codetable.net/decimal/8211) character (`–`, not a dash) to an axis title or a figure title will prevent the figure from being retrieved via `getImage`.

### Repo Steps:
1) Create a figure
2) Add the En Dash character: `–` to the title and/or axis title
3) Retrieve the figure via the Node.js SDK
4) Observe the following error output:
```
{ Error: Bad response status code 500
    at ClientRequest.handleResponse (/.../node_modules/plotly/index.js:237:25)
    at Object.onceWrapper (events.js:324:30)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:439:20)
    at emitOne (events.js:125:13)
    at TLSSocket.emit (events.js:221:7)
    at addChunk (_stream_readable.js:265:12) msg: undefined }
```

**Comment by scjody** [comment]
@SpencerKaiser Thanks for the report. Unfortunately this library has not seen much use by our customers so we're not able to spend significant resources maintaining it. However it is an open source project and we welcome a fix from the community for this issue.

Note that the node.js library is using currently performing image generation using a legacy endpoint (`/apigenimage`). Switching to the new endpoint, [available and documented here](https://api.plot.ly/v2/images), is likely to fix this issue as well as #55. The new endpoint takes the same JSON body but [authentication has changed somewhat](https://api.plot.ly/v2/#authentication).

**Comment by SpencerKaiser** [comment]
@scjody thanks for the update. I used Plot.ly as part of my company's CI/CD solution along with Artillery.io to generate performance test graphs for some of our new services. If we scale things up and get a license, I may try to update the SDK for that new endpoint!
