### ISSUE TITLE
Bad response 301

### ISSUE THREAD

**Issue by handihow** [plotly/plotly-nodejs#62]
I have a bad response 301 error on the getImage() function

This cloud function was running fine for months. 

{ Error: Bad response status code 301
    at ClientRequest.handleResponse (/srv/node_modules/plotly/index.js:237:25)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:552:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12) msg: undefined }

I have not changed anything in my code base.

Is there some type of service outage?

**Comment by nicolaskruchten** [comment]
We have recently changed the domain name of Chart Studio Cloud from `plot.ly` to `chart-studio.plotly.com`, and it looks like this library does not accept the redirection requests... I'll see what I can do about pushing out a patch with the new URL.

**Comment by handihow** [comment]
thanks Nicolas

**Comment by 2dvisio** [comment]
same here

**Comment by 2dvisio** [comment]
I have temporarily fixed it by overriding the plot.ly URLs in the file `node_modules/plotly/index.js` with chart-studio.plotly.com.

**Comment by nicolaskruchten** [comment]
From reading [the source](https://github.com/plotly/plotly-nodejs/blob/master/index.js#L15), it appears that the `username` parameter can be either a string or an object, so passing in an object with `username` and `apiKey` keys, and a `host` key with value `'chart-studio.plotly.com'` should do it, without needing a new release.

**Comment by handihow** [comment]
this works for me thanks

**Comment by 2dvisio** [comment]
Have tried after undoing my fix and it works for me as well.

**Comment by shaedmorgan** [comment]
I'm running into this same issue now months later. Code was working just fine until it all of the sudden stopped working. I tried implementing the updated URL to no avail. Error message is almost exactly the same as above, but I'm getting a 500 code instead of the 301.

Any ideas?

Code:
![image](https://user-images.githubusercontent.com/71141995/102732097-c42c4600-4307-11eb-8d75-edd16d4f9288.png)

Error:
![image](https://user-images.githubusercontent.com/71141995/102731971-58e27400-4307-11eb-97bb-9f786acc9908.png)
